openapi: 3.0.0
info:
  title: Job Application API - UsersController
  description: API endpoints for managing users.
  version: 1.0.0

paths:
  /users/index:
    get:
      summary: Retrieve list of users
      operationId: showIndex
      responses:
        '200':
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /users/delete/{id}:
    get:
      summary: Delete a user by ID
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user to delete
      responses:
        '302':
          description: User deleted successfully and redirected to user list

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the user
        username:
          type: string
          description: Username of the user
        email:
          type: string
          format: email
          description: Email address of the user
        role:
          type: string
          description: Role of the user
      required:
        - username
        - email
        - role
